### ISSUE TITLE
论文实验复现问题

### ISSUE THREAD

**Issue by MiXia7** [FeipengMa6/PriSA#8]
作者你好，我想要复现您的实验但是运行了main.py跑了一轮后遇到了如下问题，请问怎么解决？

Traceback (most recent call last):
  File "main.py", line 125, in <module>
    trainer.train()                    
  File "D:\PriSA-main\module\trainer\trainer_base.py", line 56, in train
    train_loss,train_metric_dict = self.train_one_epoch(epoch)
  File "D:\PriSA-main\module\trainer\prisa_trainer.py", line 114, in train_one_epoch
    for batch in self.train_loader:
  File "C:\Users\Axiao\.conda\envs\prisa\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\Axiao\.conda\envs\prisa\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\Axiao\.conda\envs\prisa\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Axiao\.conda\envs\prisa\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by Kokonoe-Rin** [comment]
[Uploading image.png…]()

**Comment by MiXia7** [comment]
![image](https://github.com/FeipengMa6/PriSA/assets/141403939/7784e082-70b3-4bb6-881b-bbb763df5262)

**Comment by lxq666666** [comment]
你好，能提供sims数据集及其训练过程吗，dataset文件中没有提供sims数据加载及其处理代码
